### PR TITLE
Task 020

### PR DESCRIPTION
**Pull request by akaaariii**
@pmvald I have read the web component guide and followed the tutorials. Then, I tried to follow the instruction but I couldn’t apply styles when `check-box` is `active`. I'm not sure but I might misunderstand part2. Could you please check my code and let me know if I missed something. Thank you.

### CODE REVIEW

**Comment by j-ae** [comment]
I think the problem is that the shadow-dom is isolated with own parent dom as its purpose.
If you check with F12(Developer mode), the 'active' is on the parent dom
```
<check-box label="Some text" class="default active"> <<< parent dom
  #shadow-root  <<< shadow dom
</check-box>
```
Therefore, the shadow-dom doesn't care about the toggle active change on the parent dom.

My approach is adding a modifier to "s-check-box--active" beside 's-check-box' like below.
```
updateClass() {
  if (this.state) 
  {
    this.classList.add("active")
    this.shadowRoot.querySelector('.s-check-box').classList.add("s-check-box--active")
  }
  else
  {
    this.classList.remove("active");
    this.shadowRoot.querySelector('.s-check-box').classList.remove("s-check-box--active")
  } 
  console.log(this.classList.contains('active'))
}
```

For this approach, you should delete this.updateClass() in connectedCallBack() << I don't know why you update something at init function.
and add below code in the hard coding <style>. 
```
.s-check-box.s-check-box--active > div {
  display: block;
}
```

Maybe this approach is not right answer, so @pmvald will give you better anwser later.

**Comment by akaaariii** [comment]
Hi, @j-ae 
Thank you for your suggestion!

**Comment by pmvald** [comment]
@akaaariii I made some changes and made a new commit. Please study my changes, in particular note:
- I defined a custom checkbox, which does not render anything in the shadow DOM (only rely on its html content)
- No need to bother with BEM when styling a web component. BEM is used to avoid name conflics when styling many elements using a single stylesheet. In web component elements css is isolated and we can even directly address tags (that's one of the main feature of web components) 
- I used slot to import the inner text into the label in the shadow DOM (learn about slot)
- I used [css part](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) to expose the box section to external style sheets (learn about css ::part)

Once you feel ready, do the same thing with min-max-box (for this element I guess we have no custom version ...)

**Comment by akaaariii** [comment]
@pmvald I'm done with min-max-box. Could you check my code, please? Thank you.

**Review by pmvald — APPROVED** [review]

**Comment by pmvald** [comment]
@akaaariii Ok good! I made some enhancements, you may review them. Particularly notice how I used css variables for a more dynamic and option-full component. Now I think it is good enough. For now don't worry about the radiobox. I'll have to simplify it first, and then I'll make a separate task for it. radiobox is more complicated than all these ...

**Pull request merged**
